Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 79, in add_checklist
    propagate_status_upwards(target_task)
TypeError: propagate_status_upwards() missing 2 required positional arguments: 'task' and 'Current_user'
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 77, in add_checklist
    log_task_field_change(db, target_task.task_id, "status", old_status, target_task.status, updated_by=Current_user.employee_id)
TypeError: log_task_field_change() got an unexpected keyword argument 'updated_by'
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 43, in add_checklist
    log_task_field_change(db, task.task_id, "status", old_status, task.status, updated_by=Current_user.employee_id)
TypeError: log_task_field_change() got an unexpected keyword argument 'updated_by'
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 79, in add_checklist
    propagate_incomplete_upwards(checklist.checklist_id, db,Current_user)
  File "D:\Task Management System Final code\Checklist\functions.py", line 133, in propagate_incomplete_upwards
    parent_task_id = parent_tasks[0]
                     ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 79, in add_checklist
    if target_task.task_type == TaskType.Normal and (target_task.status == TaskStatus.Completed or target_task.status == TaskStatus.In_Review):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Task Management System Final code\Checklist\functions.py", line 133, in propagate_incomplete_upwards
    parent_task_id = parent_tasks[0]
                     ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2025-05-10 10:05:02,919 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:05:27,218 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:05:27,221 - create_checklist - INFO - Task found: task_id=22, type=TaskType.Normal
2025-05-10 10:05:27,227 - create_checklist - INFO - Checklist created with ID=31
2025-05-10 10:05:27,231 - create_checklist - INFO - Checklist created with ID=32
2025-05-10 10:05:27,237 - create_checklist - INFO - Checklist created with ID=33
2025-05-10 10:05:27,237 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:07:21,198 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:07:21,198 - create_checklist - INFO - Task found: task_id=23, type=TaskType.Review
2025-05-10 10:07:21,215 - create_checklist - INFO - Review task 23 status updated to In_ReEdit
2025-05-10 10:07:21,215 - create_checklist - INFO - Checklist created with ID=34
2025-05-10 10:07:21,215 - create_checklist - INFO - Checklist created with ID=35
2025-05-10 10:07:21,232 - create_checklist - INFO - Checklist created with ID=36
2025-05-10 10:07:21,232 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:09:25,668 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:09:25,671 - create_checklist - INFO - Task found: task_id=24, type=TaskType.Normal
2025-05-10 10:09:25,672 - create_checklist - INFO - Checklist created with ID=38
2025-05-10 10:09:25,681 - create_checklist - ERROR - Unexpected error occurred
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 79, in add_checklist
    propagate_incomplete_upwards(checklist.checklist_id, db, Current_user)
  File "D:\Task Management System Final code\Checklist\functions.py", line 136, in propagate_incomplete_upwards
    parent_task_id = parent_tasks[0]
                     ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2025-05-10 10:10:46,130 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:10:46,132 - create_checklist - INFO - Task found: task_id=24, type=TaskType.Normal
2025-05-10 10:10:46,135 - create_checklist - INFO - Checklist created with ID=39
2025-05-10 10:10:46,142 - create_checklist - ERROR - Unexpected error occurred
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 79, in add_checklist
    if target_task and target_task.task_type == TaskType.Normal and target_task.status in [TaskStatus.Completed, TaskStatus.In_Review]:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Task Management System Final code\Checklist\functions.py", line 136, in propagate_incomplete_upwards
    parent_task_id = parent_tasks[0]
                     ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2025-05-10 10:10:51,925 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:10:51,928 - create_checklist - INFO - Task found: task_id=24, type=TaskType.Normal
2025-05-10 10:10:51,933 - create_checklist - INFO - Checklist created with ID=40
2025-05-10 10:10:51,963 - create_checklist - INFO - Checklist created with ID=41
2025-05-10 10:10:51,965 - create_checklist - INFO - Checklist created with ID=42
2025-05-10 10:10:51,969 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:15:16,241 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:15:16,241 - create_checklist - INFO - Task found: task_id=23, type=TaskType.Review
2025-05-10 10:15:16,257 - create_checklist - INFO - Review task 23 status updated to In_ReEdit
2025-05-10 10:15:16,257 - create_checklist - INFO - Checklist created with ID=43
2025-05-10 10:15:16,281 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:26:12,669 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:26:12,675 - create_checklist - INFO - Task found: task_id=35, type=TaskType.Review
2025-05-10 10:26:12,684 - create_checklist - INFO - Review task 35 status updated to In_ReEdit
2025-05-10 10:26:12,684 - create_checklist - INFO - Checklist created with ID=49
2025-05-10 10:26:12,702 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:41:44,056 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:41:44,068 - create_checklist - INFO - Task found: task_id=36, type=TaskType.Normal
2025-05-10 10:41:44,072 - create_checklist - INFO - Checklist created with ID=51
2025-05-10 10:41:44,089 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:41:58,166 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:41:58,169 - create_checklist - INFO - Task found: task_id=36, type=TaskType.Normal
2025-05-10 10:41:58,174 - create_checklist - INFO - Checklist created with ID=52
2025-05-10 10:41:58,188 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:45:08,403 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:45:08,409 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:45:08,409 - create_checklist - INFO - Review task 38 status updated to In_ReEdit
2025-05-10 10:45:08,425 - create_checklist - INFO - Checklist created with ID=54
2025-05-10 10:45:08,441 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:45:08,443 - create_checklist - ERROR - Unexpected error occurred
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 114, in add_checklist
    "checklist_progress": checklist_progress
                          ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'checklist_progress' where it is not associated with a value
2025-05-10 10:46:08,938 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:46:08,944 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:46:08,946 - create_checklist - INFO - Review task 38 status updated to In_ReEdit
2025-05-10 10:46:08,951 - create_checklist - INFO - Checklist created with ID=55
2025-05-10 10:46:08,963 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:46:08,965 - create_checklist - ERROR - Unexpected error occurred
Traceback (most recent call last):
  File "D:\Task Management System Final code\Checklist\Create_Checklist.py", line 114, in add_checklist
    "checklist_progress": checklist_progress if checklist_progress else "0/0",
                                                ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'checklist_progress' where it is not associated with a value
2025-05-10 10:48:14,251 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:48:14,263 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:48:14,266 - create_checklist - INFO - Review task 38 status updated to In_ReEdit
2025-05-10 10:48:14,269 - create_checklist - INFO - Checklist created with ID=56
2025-05-10 10:48:14,280 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:48:28,692 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:48:28,706 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:48:28,707 - create_checklist - INFO - Review task 38 status updated to In_ReEdit
2025-05-10 10:48:28,713 - create_checklist - INFO - Checklist created with ID=57
2025-05-10 10:48:28,728 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:50:30,242 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:50:30,242 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:50:30,259 - create_checklist - INFO - Review task 38 status updated to In_ReEdit
2025-05-10 10:50:30,259 - create_checklist - INFO - Checklist created with ID=58
2025-05-10 10:50:30,275 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-10 10:50:36,396 - create_checklist - INFO - POST /add_checklist called by user_id=5
2025-05-10 10:50:36,396 - create_checklist - INFO - Task found: task_id=38, type=TaskType.Review
2025-05-10 10:50:36,396 - create_checklist - INFO - Checklist created with ID=59
2025-05-10 10:50:36,416 - create_checklist - INFO - All checklists created and task updates committed successfully
2025-05-16 17:24:39,520 - create_checklist - INFO - POST /add_checklist called by user_id=2
2025-05-16 17:24:39,523 - create_checklist - INFO - Task found: task_id=7, type=TaskType.Normal
2025-05-16 17:24:39,525 - create_checklist - INFO - Checklist created with ID=11
2025-05-16 17:24:39,533 - create_checklist - INFO - All checklists created and task updates committed successfully
